A synthesied data set in relation to the suicide death rates of males and females within Ireland from the year 2008 to 2018.  This data set will 100 point of data which will have five different variables including: year, gender, suicide rate, age, county. It is important to note the data generated in not factually correct and is randomly generated. Random numbers will be randomly generated between 300 and 550 for male suicide rates and between 50 and 150 for females suicide rates for the years between 2008-2018.These values are similar to actual death suicide rates in Ireland.

Please see link below showing the actual suicde death rates recorded in Ireland over the last 18 years:
(https://data.gov.ie/dataset/suicide-death-rates-by-year-sex-and-statistic/resource/50013e7a-ec8d-4676-b966-77ba22a23a56

Therefore each time the script is run, different results will be produced.

In [43]:
#import numpy as np
import numpy as np

#import pandas as pd
import pandas as pd

In [48]:


from numpy.random import randint
# generate random integer values
#https://machinelearningmastery.com/how-to-generate-random-numbers-in-python/


#The x values will represent the year. In the datasets generated below, the last 10 years are being recorded as x values.
#The x values will remain the same through out the dataset.
a = [2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018]

# generate ten random numbers to represent the male suicide rate in Ireland for each year from 2008 to 2018.
b = randint(300, 500, 10)
print(b)
# generate 10 random to represent the male suicide rate in Ireland for each year from 2008 to 2018.
c = randint(50, 150, 10)
print(c)

age = randint(15, 75, 100)
print(age)

county = ['Carlow', 'Cavan', 'Clare', 'Cork', 'Donegal','Dublin','Galway', 'Kerry', 'Kildare', 'Kilkenny', 'Laois', 'Leitrim', 'Limerick', 'Longford', 'Louth', 'Mayo', 'Meath', 'Monaghan', 'Offaly', 'Roscommon', 'Sligo', 'Tipperary', 'Waterford', 'Westmeath', 'Wexford', 'Wicklow']
resultscounty= random.choice(county)
print(resultscounty)
          
import random 
gender = ['male', 'female']
results = random.choice(gender)
print(results)

[404 343 305 403 419 452 323 401 332 441]
[ 87  51  59 116 141 147 108  78  85  79]
[18 65 58 56 27 69 69 28 36 50 15 71 58 51 23 70 74 70 49 71 65 20 65 24 16
 27 73 33 44 47 31 48 16 64 68 41 32 58 59 71 39 21 68 31 19 28 30 40 32 67
 51 68 57 67 23 58 49 63 55 54 70 38 39 64 36 51 49 51 72 45 53 65 52 30 28
 53 24 44 31 48 26 43 43 63 56 21 39 68 40 72 19 64 31 64 42 45 19 74 28 42]
Kilkenny
female


In [47]:
from random import choice

class Person:
  genders = ('Male', 'Female', 'Female')
  def __init__(self, name):
      self.name = name
      self.gender = choice(Person.genders, 100)
        print
        

IndentationError: unexpected indent (<ipython-input-47-685aef97f470>, line 8)

In [50]:
suicide_data = {[age], [county],[gender]}
df = pd.dataframe(suicide_data)
df

TypeError: unhashable type: 'list'

In [27]:
import pandas as pd

data = (b, c, age)
pd.DataFrame(data, columns=["Foo", "Bar"])

ValueError: DataFrame constructor not properly called!

In [22]:
import pandas as pd
data = {'year':['2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018'],'Age':[randint(15,70,100)]}
df = pd.DataFrame(data, index=['rank1','rank2','rank3','rank4'])
print(df)

ValueError: could not broadcast input array from shape (11) into shape (4)

In [9]:
#print the years used as the x values
a

[2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018]

In [10]:
b

NameError: name 'b' is not defined

In [38]:
PrintTable(data, column_captions, column_widths, text_aligns).print()

NameError: name 'PrintTable' is not defined

In [39]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [41]:
from pydataset import data
male = data('male')
show()

ModuleNotFoundError: No module named 'pydataset'

In [65]:
import pandas as pd

In [107]:
# Plot the best fit line.
import matplotlib.pyplot as plt

plt.plot(a, b, 'k.', label='Original data')
plt.legend()
plt.show()

ValueError: x and y must have same first dimension, but have shapes (11,) and (10,)

In [114]:
import numpy as np
import pandas as pd

categories=('male','female')

data = {
            'suicide deaths':      np.random.randint(300,500, size=100), 
            'category':  np.random.choice(categories, 100),
            'year':     (2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018)
       }

df = pd.DataFrame(data)
print(df)


ValueError: arrays must all be same length

In [100]:
x = a
y = b

x
y

[2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018]

array([310, 482, 396, 382, 498, 494, 371, 476, 354, 315])

In [102]:
# First calculate the average suicide rate of males in Ireland from the years 2008 to 2018.
b_avg = np.mean(b)

In [103]:
#print average yearly suicide rate of males in Ireland
b_avg

407.80000000000001

In [109]:
# First calculate the average suicide rate of females in Ireland from the years 2008 to 2018.
c_avg = np.mean(c)

#print average yearly suicide rate of females in Ireland
c_avg

103.8

In [ ]:
import pandas as pd
data = {'year':['Tom', 'Jack', 'Steve', 'Ricky'],'Age':[28,34,29,42]}
df = pd.DataFrame(data, index=['rank1','rank2','rank3','rank4'])
print df

# References:

https://www.youtube.com/watch?v=KzqSDvzOFNA
https://data.gov.ie/dataset/suicide-death-rates-by-year-sex-and-statistic/resource/50013e7a-ec8d-4676-b966-77ba22a23a56
https://stackoverflow.com/questions/43991548/when-defining-a-python-class-how-to-set-a-random-variable-in-it
https://www.irishtimes.com/news/social-affairs/men-account-for-almost-80-of-suicides-recorded-in-state-1.3235494